### ISSUE TITLE
Using postman instead

### ISSUE THREAD

**Issue by alarcia** [edent/Renault-Zoe-API#11]
Hello! Thanks for the good work.
I want to use postman, but I am having trouble.
The headers part is clear, but I don't know where to put the `-d` of cURL in postman. I tried both `body` and `params`, but the result is the same.

In `body`:
![image](https://user-images.githubusercontent.com/6407366/37958879-fe111d1a-31b1-11e8-8e06-39e3b086f91b.png)

In `params`:
![image](https://user-images.githubusercontent.com/6407366/37958940-1e1d8ea4-31b2-11e8-815c-f22bee62659c.png)

Response:
``` json
{
    "code": 1203244171,
    "message": "Required request body content is missing: org.springframework.web.method.HandlerMethod$HandlerMethodParameter@77bcca65",
    "timestamp": 1522142947676
}
```

Is it possible that the API has changed?

**Comment by edent** [comment]
The API hasn't changed. I'm not familiar with Postman, but it looks like you need to send JSON in the raw tab. See https://www.getpostman.com/docs/v6/postman/sending_api_requests/requests

**Comment by alarcia** [comment]
Thank you very much, that did it, and shame on me for not researching enough.

**Comment by edent** [comment]
Don't beat yourself up. We were all new once. Glad the API is useful to you.
