### ISSUE TITLE
Creation of a Python Package for code reusing

### ISSUE THREAD

**Issue by oncleben31** [edent/Renault-Zoe-API#15]
Hello thank for your work to create this API.
I'm planning to re-use your work to create an addon to https://github.com/home-assistant/home-assistant
To do so they request all API logic should be in a python  package that we can install with a `pip` command. The code I will write will be the interface between home-assistant methods and your module.

Do you plan to do so ?
I can doing it but it will required to reinject all your future commit in my repo. Not so effcient.

What is your point of view?

**Comment by edent** [comment]
Brilliant idea! I'm giving my Zoe back in a few weeks, so I don't have time to write a pip package.

Good luck with this, sounds like a brilliant project.

**Comment by epenet** [comment]
I missed this converstation when I started building my own Home Assistant component.
I got my custom_component working, it's available on https://github.com/epenet/hassRenaultZE.

I also took the opportunity to make a copy of the renaultze code in async format (using aiohttp).

What is the best way to get a pip package going?

**Comment by oncleben31** [comment]
good. To make a pip package. Go to Pypi.org. Read doc... Search Google...
I've done a pip package for a weather alert in France. You can check the structure https://github.com/oncleben31/vigilancemeteo

**Comment by oncleben31** [comment]
> Brilliant idea! I'm giving my Zoe back in a few weeks, so I don't have time to write a pip package.
> 
> Good luck with this, sounds like a brilliant project.

@edent  Will you still maintain the repo and merge the pull requests ?

**Comment by edent** [comment]
No, I will not. Sorry.

I don't have this car any more so I won't be able to check the functionality of the code.

Please fork this repo and maintain it yourself.

**Comment by oncleben31** [comment]
OK thanks it clear. @epenet do you volunteer to maintain the fork? :wink:

**Comment by oncleben31** [comment]
We have now a new API and a package by https://github.com/jamesremuscat/pyze.
We can close the issue.
